## The first function, makeVector creates a special "vector", which is really a list containing a function to
## 1. Set the value of the matrix
## 2. Get the value of the matrix
## 3. Set the value of the inverse of the matrix
## 4. Get the value of the inverse of the matrix

##Detailed explanation and sample results and validations shown in the end. 

## makeCacheMatrix is a list of the functions mentioned above in the respective order

makeCacheMatrix <- function(x = matrix()) {
  matrix <- NULL
  setmatrix <- function(y = matrix()) {
    x <<- y
    matrix <<- NULL
  }
  getmatrix <- function() x
  setInverse <- function(solve) matrix <<- solve
  getInverse <- function() matrix
  list(setmatrix = setmatrix, getmatrix = getmatrix,
       setInverse = setInverse,
       getInverse = getInverse)
  
}


## Similar to the cacheMean function defined in the description of the assignment, cacheSolve helps compute
## the inverse of the matrix defined and stored in makeCacheMean, however it first checks if the inverse was already computed 
## so as to not reinvent the wheel. Assumption is only square invertible matrices are inputted. 

cacheSolve <- function(x, ...) {
  matrix <- x$getInverse()
  if(!is.null(matrix)) {
    message("getting cached data")
    return(matrix)
  }
  data <- x$getmatrix()
  matrix <- solve(data, ...)
  x$setInverse(matrix)
  matrix
  
        ## Return a matrix that is the inverse of 'x'
}

## Defining a matrix A

## > A<- matrix(c(4,3,3,2),nrow=2, ncol=2)
##> A
##[,1] [,2]
##[1,]    4    3
##[2,]    3    2

## Assigning thelist generated by makeCacheMatrix to 'a'
##> a <- makeCacheMatrix(A)

## Getting the matrix stored in the list a (the second element is the function that returns the value of matrix stored
## in this case it is A)

##> a$getmatrix()
##[,1] [,2]
##[1,]    4    3
##[2,]    3    2

## Calling Function cacheSolve on 'a' which returns it's Inverse
##> cacheSolve(a)
##[,1] [,2]
##[1,]   -2    3
##[2,]    3   -4

## Calling the function cacheSolve on 'a' again, the output is message that says "Getting cached data" to return 
## the inverse which was computed earlier

##> cacheSolve(a)
##Getting cached data
##[,1] [,2]
##[1,]   -2    3
##[2,]    3   -4

## Testing that the function works correctly by performing matrix multiplication on A(a$getmatrix) and its Inverse(cacheSolve(a))
## If all works well, the output would be an I matrix that is 2 by 2
##> (a$getmatrix())%*%cacheSolve(a)
##getting cached data
##[,1] [,2]
##[1,]    1    0
##[2,]    0    1

##The result proves the logic and syntax are indeed working as intended






